services:
  porkbun-ddns:
    image: mietzen/porkbun-ddns:latest
    container_name: porkbun-ddns
    restart: unless-stopped

    environment:
      APIKEY: "pk1_1e670b9b12c75fc7c24694e572e12882380b08466c83d62b54a45f1aa1e580bc"
      SECRETAPIKEY: "sk1_c71b48baed681de10e03edff9b2b3c3bf569b5166ccea10bc705cd1f78d6e3f7"
      DOMAIN: "kai.coach"
      SUBDOMAINS: "jellyfin,seerr"
      INTERVAL: "300"
